### ISSUE TITLE
Unix Domain Socket

### ISSUE THREAD

**Issue by christopherlai** [beam-telemetry/telemetry_metrics_statsd#17]
@arkgil any plans on supporting UDS option?

**Comment by arkgil** [comment]
@christopherlai it'd be great to support it. Feel free to take a stab if you want! Unfortunately, I'm currently lacking bandwidth to do it myself.

Does any other implementation than DogStatsD support it?

**Comment by kamilkowalski** [comment]
A quick search told me [statsd/statsd](https://github.com/statsd/statsd) doesn't support it, but [stripe/veneur](https://github.com/stripe/veneur) does.

I could use that option, so I'll be happy to contribute.
