### ISSUE TITLE
Crash at event_handler.ex:63 if tag value is missing - intentional?

### ISSUE THREAD

**Issue by simpers** [beam-telemetry/telemetry_metrics_statsd#43]
I have a question regarding `TelemetryMetricsStatsd` and its `EventHandler`. In our environments we very subtly lose all of our metrics due to a crash which we suspect is caused by `Map.fetch!/2` as a tag value is missing.

Is it intentional to crash here if the value does not exist for a given tag? If that is the case, is this documented?

Our metrics.ex is currently very long and messy due to how tricky it is to manage the tags for different kinds of metrics, and I was hoping that it would be fine to configure the metrics such that if a value for the key exists, just use that, so that we can reuse a lot of functions. This means that more of the tag handling is common for all metrics, and the exceptions are handled more cleanly.

Currently this behaviour is not the same as the `ConsoleReporter` that I tend to use when I develop as we do not want to report any metrics to anywhere during development, but if it looks this way I either need to do that or to implement some kind of tests that copy this behaviour such that we catch the crash before deployment. Currently this process dies upon deployment and then we're blind.

This is from the tag 0.4.0 I think, but the line still exists in latest.

https://github.com/beam-telemetry/telemetry_metrics_statsd/blob/cda8cca8b204c8c870b2da691817bab7bd6dc4f1/lib/telemetry_metrics_statsd/event_handler.ex#L63

**Comment by arkgil** [comment]
Hi there 👋 The problem with simply excluding missing tags is that with the "standard" reporter the tags make up the metric name published to StatsD. For example with

```elixir
counter("my_app.http_req.stop.count", tags: [:method, :status])

:telemetry.execute([:my_app, :http_req, :stop], %{}, %{method: "GET", status: 200})
```

the reporter would publish `my_app.http_req.stop.count.GET.200`. This is because the classic StatsD protocol doesn't support explicit tagging, and appending segments to the metric name is the only way to get multi-dimensional metrics.

**Comment by simpers** [comment]
Makes sense. This makes it very hard to have generic tag handling though. My case is that I almost always have a set of tags, `[:environment, :client_type]`, and then I have more specific ones depending on what it is. The type of channel or such. But due to the above it seems I'll have to create a function for each metric I define to guarantee that it won't crash?

**Comment by simpers** [comment]
Would it be possible to add a configuration for this of some kind? There are several times where the same telemetry event may miss certain meta data and I won't be able to jack it in before the reporter will try to send it off. This happens because different client types have different flows of authentication amongst other things. So all tags aren't available at all times across the board. If not, any suggestions?

**Comment by arkgil** [comment]
I guess it should be fine to filter out the metrics with missing tag values in the standard formatter. Not sure what would be the best behaviour for the datadog formatter, though - send empty tag values or don't send them at all?

**Comment by simpers** [comment]
> I guess it should be fine to filter out the metrics with missing tag values in the standard formatter. Not sure what would be the best behaviour for the datadog formatter, though - send empty tag values or don't send them at all?

Could it be a setting? I don't know what DataDog does if they get an empty tag value, but if they don't do anything in particular then maybe it does not matter?

**Comment by arkgil** [comment]
I checked and sending empty tags for DataDog is fine. We can relax the requirement for tag values existence then. We simply default for an empty string as a value if the value doesn't exist.

**Comment by simpers** [comment]
Sorry, I missed this but that's great to hear.
