### ISSUE TITLE
Support `telemetry==1.0.0`

### ISSUE THREAD

**Issue by amartsinovich-dialpad** [beam-telemetry/telemetry_metrics_statsd#62]
The package depends on `telemetry ~> 0.4` while version `1.0.0` is available. There seems to be no changes needed, just a version bump?

**Comment by arkgil** [comment]
Fixed in #63

**Comment by arkgil** [comment]
@amartsinovich-dialpad 0.6.1 is now available with support for Telemetry 1.0 https://hex.pm/packages/telemetry_metrics_statsd/0.6.1 :) Thanks!
