### ISSUE TITLE
Thank you for writing beautiful tests

### ISSUE THREAD

**Issue by pzel** [beam-telemetry/telemetry_metrics_statsd#67]
Hey team, just wanted to drop a thank-you note for your excellent test suite. I was trying to figure out whether I can submit multiple measurements to one event, and figured I'd just look at the tests.

Sure enough, there is a test case demonstrating both the use of the API and the wire format that comes out.

https://github.com/beam-telemetry/telemetry_metrics_statsd/blob/main/test/telemetry_metrics_statsd_test.exs#L200-L227

Keep up the excellent work!!!

**Comment by arkgil** [comment]
Hey Simon, thanks for the kind words! I really appreciate it ☺️
