### ISSUE TITLE
Allow non standard datadog metric types?

### ISSUE THREAD

**Issue by btkostner** [beam-telemetry/telemetry_metrics_statsd#72]
Hello :wave: I wanted to get an answer to this question before I started the work, but would a PR to add support for the non standard Datadog service check be accepted?

Datadog accepts service checks via statsd. They show up differently (more intuitively for a bool value) in the Datadog interface.
https://docs.datadoghq.com/developers/service_checks/dogstatsd_service_checks_submission/
https://github.com/DataDog/datadog-go/blob/553de96e699a42be8b401607fbbbce81d4942790/statsd/statsd.go#L647

I haven't dug too deep, but my plan was to add a function head to `format_metric_value` where if it includes some special tag it would be outputted as a service check. Open to better ideas though.

**Comment by arkgil** [comment]
Hi Blake 👋 Thanks for a suggestion! How do you imagine the service checks would be defined? Can you give an example of a service check that some would want to implement with this library, and how that would look like?

**Comment by arkgil** [comment]
@btkostner thanks! In that case, I think this would be best implemented as a new reporter option for the last value. Currently we support a `report_as: :counter` option for the counter metric:

https://github.com/arkgil/telemetry_metrics_statsd/blob/1695991fb60a3323ff35d08640b5016d2d94421d/lib/telemetry_metrics_statsd/formatter/standard.ex#L75-L80

You could add a `report_as: :service_check` option to `last_value`. Ideally we would validate that it's only set if the DataDog formatter is used. WDYT?

**Comment by btkostner** [comment]
That actually works out perfectly. I didn't realize we were already doing something kinda similar. I'll try to get a PR up this week for review :+1:
