### ISSUE TITLE
Is IPv6 supported?

### ISSUE THREAD

**Issue by cheerfulstoic** [beam-telemetry/telemetry_metrics_statsd#78]
It seems like the `opts` given to `:gen_udp.open/2` maybe needs to have `:inet6` given to enable support for IPv6.   If so, and if I'm reading the [UDP module](https://github.com/beam-telemetry/telemetry_metrics_statsd/blob/6f0df1e21fbb68df05f8040f9d85c0e1c0a05c47/lib/telemetry_metrics_statsd/udp.ex) right, that's not currently possible.

Does that all seem right to you?  I could potentially make a PR for this, but I wanted to sanity check first 😄

**Comment by cheerfulstoic** [comment]
Some background on what I'm trying to do, in case it helps: https://community.fly.io/t/using-wireguard-to-connect-to-service-on-my-laptop/13788/3

**Comment by cheerfulstoic** [comment]
I just tried a [patched version](https://github.com/cheerfulstoic/telemetry_metrics_statsd/blob/main/lib/telemetry_metrics_statsd/udp.ex) which hardcodes `:inet6` as an option, but that didn't seem to help anything.  Maybe it's a network config issue... 🤔   Happy to have advice if you have any 😄

**Comment by mbuffa** [comment]
Hello there!

Just trying to configure telemetry on fly.io myself, and I think you might be up to something.

In my case, I got a DogStatsD agent running in a container as a dedicated Fly.io app. Fly has internal DNS records and digging the DNS entry on my app works (https://fly.io/docs/reference/private-networking/).

However, calling `:inet.gethostbyname("my-app-name.internal")` doesn't, it's used by the library, and it has a inet6 option.

**Comment by cheerfulstoic** [comment]
Ok, after a bunch of poking I think that adding the `:inet6` option does help.  I think that my fork changes weren't going up to fly.io before 😅
