### ISSUE TITLE
upgrade `telemetry_metrics` dep from 0.6 -> 1.0

### ISSUE THREAD

**Issue by sc-yan** [beam-telemetry/telemetry_metrics_statsd#91]
since telemetry_metrics released 1.0, ([ref](https://github.com/beam-telemetry/telemetry_metrics/blob/main/CHANGELOG.md)) can we upgrade it to 1.0 in mix?
https://github.com/beam-telemetry/telemetry_metrics_statsd/blob/70dc6ddfc3ffb01d53a4bc46655dfc03d05233ad/mix.exs#L42

I created a PR https://github.com/beam-telemetry/telemetry_metrics_statsd/pull/93

**Comment by bbil** [comment]
Yeah, it would be nice to get this version bump in. Dependabot is making PRs to update `telemetry_metrics` to 1.0, but then that breaks this.

**Comment by aselder** [comment]
Love to get this merged! There are no changes between 0.6.2 and 1.0.0 of telemetry.

**Comment by arkgil** [comment]
#93 with this change has been just merged in.
